### ISSUE TITLE
Volatile GPU-Util  is low and fluctuant

### ISSUE THREAD

**Issue by weiguochow** [poier/PreView#5]
Hi, Thank you for your codes. And I changed to another benchmark, but the volatile gpu-util is very low and fluctuant.  Can yo give me some advice about it. Thank you very much!

**Comment by poier** [comment]
Hi, that the GPU utilization is low or fluctuating is usually because other tasks, like loading data from disk or to/from GPU memory, takes time and the GPU has to "wait" for them.
You may be able to use more "workers" for loading, i.e., increase `args.num_loader_workers`, or a faster disk and can increase training/testing speed. (Also see the "Training/Testing speed" section of the README)

**Comment by weiguochow** [comment]
I got it, thank you very much!
